### ISSUE TITLE
High score board

### ISSUE THREAD

**Issue by RinkAttendant6** [RinkAttendant6/threatsweeper#4]
It would be nice to keep track of a user's top 10 best times and display this somewhere on the user interface. The data can be kept in the state of the React component (reset on reload) or using a [Web Storage](https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API) mechanism.

**Comment by devops1107** [comment]
Hi!, I have try to  install, that is failed
Please share a guide for this repo. Thanks for advantage

**Comment by RinkAttendant6** [comment]
Can you share the error that you encountered while installing? I'm able to install from scratch using the instructions in the README file.

**Comment by devops1107** [comment]
thanks for letting me
I want to share my screen via skype. Sorry , please contact me.

**Comment by RinkAttendant6** [comment]
Sorry, I no longer use Skype.
I'd be glad to try and assist you if you paste the error message or even a screenshot of the error message here.

**Comment by devops1107** [comment]
Thanks for reply
https://docs.google.com/document/d/1k6gm9ozjQ8kkBNT5LZKIf5OyuSkgfuLZTsYvlE1Cx1Y/

If you got issue, I will remove this comment. I hope as well with you
